COMPANY_NAME_OVERRIDES: dict[str, str] = {
    "000660.KS": "SK hynix Inc.",
    "005930.KS": "Samsung Electronics Co., Ltd.",
    "0700.HK": "Tencent Holdings Limited",
    "0939.HK": "China Construction Bank Corporation",
    "1288.HK": "Agricultural Bank of China Limited",
    "1398.HK": "Industrial and Commercial Bank of China Limited",
    "2222.SR": "Saudi Arabian Oil Company",
    "AAPL": "Apple Inc.",
    "ABBV": "AbbVie Inc.",
    "AMD": "Advanced Micro Devices, Inc.",
    "AMZN": "Amazon.com, Inc.",
    "ASML": "ASML Holding N.V.",
    "AVGO": "Broadcom Inc.",
    "AZN": "AstraZeneca PLC",
    "BABA": "Alibaba Group Holding Limited",
    "BAC": "Bank of America Corporation",
    "BRK-B": "Berkshire Hathaway Inc.",
    "CAT": "Caterpillar Inc.",
    "COST": "Costco Wholesale Corporation",
    "CSCO": "Cisco Systems, Inc.",
    "CVX": "Chevron Corporation",
    "GE": "GE Aerospace",
    "GOOGL": "Alphabet Inc.",
    "HD": "The Home Depot, Inc.",
    "HSBC": "HSBC Holdings plc",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase & Co.",
    "KO": "The Coca-Cola Company",
    "LLY": "Eli Lilly and Company",
    "LRCX": "Lam Research Corporation",
    "MA": "Mastercard Incorporated",
    "MC.PA": "LVMH Moët Hennessy Louis Vuitton SE",
    "META": "Meta Platforms, Inc.",
    "MRK": "Merck & Co., Inc.",
    "MSFT": "Microsoft Corporation",
    "MU": "Micron Technology, Inc.",
    "NFLX": "Netflix, Inc.",
    "NOVN.SW": "Novartis AG",
    "NVDA": "NVIDIA Corporation",
    "ORCL": "Oracle Corporation",
    "PG": "The Procter & Gamble Company",
    "PLTR": "Palantir Technologies Inc.",
    "ROG.SW": "Roche Holding AG",
    "TM": "Toyota Motor Corporation",
    "TSLA": "Tesla, Inc.",
    "TSM": "Taiwan Semiconductor Manufacturing Company Limited",
    "V": "Visa Inc.",
    "WMT": "Walmart Inc.",
    "XOM": "Exxon Mobil Corporation",
}
